import { useContext, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import SharedContext from '../context/SharedContext';
import { fetchCatalog } from '../components/coaches/catalog';
import { trackEvent } from '../analytics/analytics';
export default function PlansPage(){
 const {countryCode,setCountryCode}=useContext(SharedContext);
 const [plans,setPlans]=useState([]), [couplePlans,setCouplePlans]=useState([]), [loading,setLoading]=useState(true), [failed,setFailed]=useState(false), [retry,setRetry]=useState(0), [duration,setDuration]=useState(24), [couple,setCouple]=useState(false);
 const region=countryCode||'DOMESTIC';
 useEffect(()=>{const controller=new AbortController();setLoading(true);setFailed(false);Promise.allSettled([fetchCatalog('plans',controller.signal),fetchCatalog('couple-plans',controller.signal)]).then(([individual,shared])=>{if(controller.signal.aborted)return;setPlans(individual.status==='fulfilled'?individual.value:[]);setFailed(individual.status==='rejected');setCouplePlans(shared.status==='fulfilled'?shared.value:[]);setLoading(false)});return()=>controller.abort()},[retry]);
 const regional=(couple?couplePlans:plans).filter(p=>p.is_active!==false && p.category?.location?.toUpperCase()===region && Number(p.price)>0 && Number(p.duration_weeks)>0);
 const durations=[...new Set(regional.map(p=>Number(p.duration_weeks)))].sort((a,b)=>a-b);
 const selectedDuration=durations.includes(Number(duration))?Number(duration):'all';
 const levelNames={junior:'Junior',juniorplus:'Junior+',senior:'Senior',expert:'Expert',elite:'Elite'};
 const order=['junior','juniorplus','senior','expert','elite'];
 const shown=regional.filter(p=>selectedDuration==='all'||Number(p.duration_weeks)===selectedDuration).sort((a,b)=>order.indexOf(a.category?.coach_level?.toLowerCase())-order.indexOf(b.category?.coach_level?.toLowerCase())||Number(a.duration_weeks)-Number(b.duration_weeks));
 const chooseMode=value=>{setCouple(value);setDuration(24);trackEvent('filter_plans',{plan_type:value?'couple':'individual',pricing_region:region})};
 return <><section className="page-intro wrap"><p className="eyebrow">Coaching, made clear</p><h1>YOUR GOALS.<br/><em>YOUR KIND OF PLAN.</em></h1><p>Solo or together, choose a timeline that works for you. Understand the support and the full price before you begin.</p></section><section className="wrap plans-section">
 <div className="couple-mode-switch plans-package-switch" aria-label="Coaching package"><button type="button" aria-pressed={!couple} onClick={()=>chooseMode(false)}><span className="package-person-icon" aria-hidden="true">01</span><span><strong>Individual</strong><small>A plan built just for you</small></span><span className="selection-dot" aria-hidden="true"/></button><button type="button" aria-pressed={couple} onClick={()=>chooseMode(true)}><span className="package-person-icon" aria-hidden="true">02</span><span><strong>Couple</strong><small>Two people. Individual goals.</small></span><span className="selection-dot" aria-hidden="true"/></button></div>
 <div className="directory-toolbar"><div className="tier-tabs" aria-label="Plan duration"><button aria-pressed={selectedDuration==='all'} onClick={()=>setDuration('all')}>All timelines</button>{durations.map(d=><button key={d} aria-pressed={selectedDuration===d} onClick={()=>{setDuration(d);trackEvent('filter_plans',{duration_weeks:d,plan_type:couple?'couple':'individual'})}}>{d} weeks</button>)}</div><label className="region-control">Pricing region<select value={region} onChange={e=>{setCountryCode(e.target.value);setDuration(24)}}><option value="DOMESTIC">India · INR</option><option value="INTERNATIONAL">International · USD</option></select></label></div>
 {loading?<p role="status">Loading coaching plans…</p>:couple&&regional.length===0?<div className="couple-empty" data-reveal><div><p className="eyebrow">Two people. One commitment.</p><h3>Shared momentum.<br/>Individual guidance.</h3><p>One coach, a common start date, and training and nutrition tailored to each person.</p><ul className="couple-benefits"><li>Individual training plans</li><li>Personal nutrition guidance</li><li>Support for both participants</li></ul></div><div className="couple-empty-state"><strong>Pricing coming soon.</strong><p>Couple packages in {region==='DOMESTIC'?'INR':'USD'} will appear here when available.</p><Link className="text-link" to="/coaches" state={{coupleMode:true}}>Explore our coaches ↗</Link></div></div>:failed&&!couple?<div className="catalogue-note"><p>Current prices are unavailable. Explore what coaching includes below, or try loading prices again.</p><button className="text-link" onClick={()=>setRetry(r=>r+1)}>Try again →</button></div>:regional.length===0?<p className="catalogue-note">No coaching plans are currently listed for this region. <Link to="/coaches">Explore coaches</Link> or contact us below.</p>:null}
 {shown.length>0&&<div className="plan-grid">{shown.map(p=><article className={`plan-card ${p.recommended?'recommended':''}`} key={p.id} data-reveal>{p.recommended&&<span className="plan-recommendation">Coach recommended</span>}<p className="eyebrow">{p.category?.coach_level_name||levelNames[p.category?.coach_level?.toLowerCase()]||p.category?.coach_level} · {couple?'Couple':'Individual'}</p><h2>{p.duration_weeks} WEEKS</h2><p className="plan-price">{region==='DOMESTIC'?'₹':'$'}{Number(p.price).toLocaleString()}<span>{couple?' total for both':' total'}</span></p><p className="plan-weekly">About {region==='DOMESTIC'?'₹':'$'}{Math.ceil(Number(p.price)/Number(p.duration_weeks)/(couple?2:1)).toLocaleString()} {couple?'per person / week':'per week'}</p><hr/><ul><li>Personalized workout {couple?'plans':'plan'}</li><li>Nutrition guidance</li><li>Regular coach check-ins</li></ul><Link className="button button-outline" to="/coaches" state={{coupleMode:couple}} onClick={()=>trackEvent('plan_interest',{plan_id:String(p.id),plan_type:couple?'couple':'individual',duration_weeks:Number(p.duration_weeks),value:Number(p.price),currency:region==='DOMESTIC'?'INR':'USD'})}>Choose your coach ↗</Link><small>Final inclusions and availability are shown on your coach’s profile.</small></article>)}</div>}
 <div className="section-heading plan-features-heading" data-reveal><div><p className="eyebrow">Find your starting point</p><h2>SUPPORT THAT<br/><em>MAKES SENSE FOR YOU.</em></h2></div></div><div className="feature-grid">{[['Personal coaching','A dedicated coach, personalized workouts and nutrition guidance, with regular check-ins to keep adjusting your plan.','Explore coaches','/coaches'],['Start with a conversation','Get to know your coach, talk through your goals, and understand the program before committing to a full coaching plan.','Find a coach','/coaches'],['Not sure what fits?','Tell us a little about your routine and preferences. Our short questionnaire helps narrow down your coach options.','Find my match','/findmycoach']].map(([t,c,l,url])=><article className="feature-card" key={t} data-reveal><h3>{t}</h3><p>{c}</p><Link className="text-link" to={url}>{l} ↗</Link></article>)}</div><div className="billing-note"><strong>A clear price before you commit.</strong><p>Programs have a fixed duration. Weekly prices are a comparison; checkout displays the total program amount. You pay once for your program. Plans do not renew automatically. Couple totals cover both participants.</p></div></section></>;
}
